{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <result.test_feature_story.TestLogin object at 0x0000028E968FB388>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failure(self):\n        # 标注测试步骤\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登陆\")\n        with allure.step(\"点击登陆之后登陆失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_feature_story.py:30: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1592733077795, "stop": 1592733077795}, {"name": "点击密码", "status": "passed", "start": 1592733077796, "stop": 1592733077796}, {"name": "点击登陆之后登陆失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"C:\\Users\\18729\\PycharmProjects\\test\\result\\test_feature_story.py\", line 30, in test_login_failure\n    assert '1' == 1\n"}, "start": 1592733077796, "stop": 1592733077796}], "attachments": [{"name": "stdout", "source": "9b9f5bff-4f6e-4a32-8d9b-c4c73818f57c-attachment.txt", "type": "text/plain"}], "start": 1592733077795, "stop": 1592733077796, "uuid": "f22b97bc-5fbc-4ce8-af7a-54fbe961834e", "historyId": "a58c5550e5c40eb80abda2e84e87077a", "testCaseId": "a0fb827149424dbc77d431148fe9f888", "fullName": "test_feature_story.TestLogin#test_login_failure", "labels": [{"name": "feature", "value": "登陆模块"}, {"name": "story", "value": "密码缺失"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-CH6E9HR5"}, {"name": "thread", "value": "15648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}