{"name": "test_step_demo[pytest]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './result/b.png'", "trace": "test_data1 = 'pytest'\n\n    @allure.testcase(\"http://github.com\")\n    @allure.feature(\"百度搜索\")\n    @pytest.mark.parametrize('test_data1', ['allure', 'pytest', 'unittest'])\n    def test_step_demo(test_data1):\n    \n        with allure.step(\"打开百度网页\"):\n            driver = webdriver.Chrome()\n            driver.get(\"http://www.baidu.com\")\n    \n        with allure.step(f\"输入搜索词:{test_data1}\"):\n            driver.find_element_by_id(\"kw\").send_keys(test_data1)\n            time.sleep(2)\n            driver.find_element_by_id(\"su\").click()\n            time.sleep(2)\n    \n        with allure.step(\"保存图片\"):\n            driver.save_screenshot(\"./result/b/png\")\n>           allure.attach.file(\"./result/b.png\", attachment_type=allure.attachment_type.PNG)\n\ntest_baidudemo.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\venv\\lib\\site-packages\\allure_commons\\_allure.py:167: in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n..\\venv\\lib\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n..\\venv\\lib\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n..\\venv\\lib\\site-packages\\pluggy\\manager.py:87: in <lambda>\n    firstresult=hook.spec.opts.get(\"firstresult\") if hook.spec else False,\n..\\venv\\lib\\site-packages\\allure_pytest\\listener.py:219: in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n..\\venv\\lib\\site-packages\\allure_commons\\reporter.py:113: in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n..\\venv\\lib\\site-packages\\pluggy\\hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n..\\venv\\lib\\site-packages\\pluggy\\manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n..\\venv\\lib\\site-packages\\pluggy\\manager.py:87: in <lambda>\n    firstresult=hook.spec.opts.get(\"firstresult\") if hook.spec else False,\n..\\venv\\lib\\site-packages\\allure_commons\\logger.py:53: in report_attached_file\n    shutil.copy2(source, destination)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python37\\lib\\shutil.py:266: in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nsrc = './result/b.png', dst = 'C:\\\\Users\\\\18729\\\\PycharmProjects\\\\test\\\\result\\\\result\\\\3\\\\f9832317-7ee2-461b-a36a-9c3fefb02a18-attachment.png'\n\n    def copyfile(src, dst, *, follow_symlinks=True):\n        \"\"\"Copy data from src to dst.\n    \n        If follow_symlinks is not set and src is a symbolic link, a new\n        symlink will be created instead of copying the file it points to.\n    \n        \"\"\"\n        if _samefile(src, dst):\n            raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\n    \n        for fn in [src, dst]:\n            try:\n                st = os.stat(fn)\n            except OSError:\n                # File most likely does not exist\n                pass\n            else:\n                # XXX What about other special files? (sockets, devices...)\n                if stat.S_ISFIFO(st.st_mode):\n                    raise SpecialFileError(\"`%s` is a named pipe\" % fn)\n    \n        if not follow_symlinks and os.path.islink(src):\n            os.symlink(os.readlink(src), dst)\n        else:\n>           with open(src, 'rb') as fsrc:\nE           FileNotFoundError: [Errno 2] No such file or directory: './result/b.png'\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python37\\lib\\shutil.py:120: FileNotFoundError"}, "steps": [{"name": "打开百度网页", "status": "passed", "start": 1592737801707, "stop": 1592737805827}, {"name": "输入搜索词:pytest", "status": "passed", "start": 1592737805827, "stop": 1592737810172}, {"name": "保存图片", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './result/b.png'\n", "trace": "  File \"C:\\Users\\18729\\PycharmProjects\\test\\result\\test_baidudemo.py\", line 23, in test_step_demo\n    allure.attach.file(\"./result/b.png\", attachment_type=allure.attachment_type.PNG)\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 167, in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\pluggy\\hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\pluggy\\manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\pluggy\\manager.py\", line 87, in <lambda>\n    firstresult=hook.spec.opts.get(\"firstresult\") if hook.spec else False,\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\allure_pytest\\listener.py\", line 219, in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\allure_commons\\reporter.py\", line 113, in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\pluggy\\hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\pluggy\\manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\pluggy\\manager.py\", line 87, in <lambda>\n    firstresult=hook.spec.opts.get(\"firstresult\") if hook.spec else False,\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\18729\\pycharmprojects\\test\\venv\\lib\\site-packages\\allure_commons\\logger.py\", line 53, in report_attached_file\n    shutil.copy2(source, destination)\n  File \"C:\\Users\\18729\\AppData\\Local\\Programs\\Python\\Python37\\lib\\shutil.py\", line 266, in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n  File \"C:\\Users\\18729\\AppData\\Local\\Programs\\Python\\Python37\\lib\\shutil.py\", line 120, in copyfile\n    with open(src, 'rb') as fsrc:\n"}, "attachments": [{"source": "f9832317-7ee2-461b-a36a-9c3fefb02a18-attachment.png", "type": "image/png"}], "start": 1592737810172, "stop": 1592737810554}], "parameters": [{"name": "test_data1", "value": "'pytest'"}], "start": 1592737801707, "stop": 1592737810556, "uuid": "09e1278e-5a0e-453a-bda1-39f5f74b3362", "historyId": "b5728ab098ee84c074c2c7c4b84b366d", "testCaseId": "e458c55b521d0555080c669f00d42f56", "fullName": "test_baidudemo#test_step_demo", "labels": [{"name": "feature", "value": "百度搜索"}, {"name": "suite", "value": "test_baidudemo"}, {"name": "host", "value": "LAPTOP-CH6E9HR5"}, {"name": "thread", "value": "2296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_baidudemo"}], "links": [{"type": "test_case", "url": "http://github.com", "name": "http://github.com"}]}